# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
  	get_provisioning_profile
    build_app(scheme: "FityIt")
    upload_to_app_store
  end

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(
    	scheme: "FityIt-Screenshots",
    	xcargs: "OTHER_SWIFT_FLAGS=\"-D SNAPSHOT\"",
    	clear_previous_screenshots: true
   	)
  end
end
