# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(
    	scheme: "FityIt-Screenshots",
    	xcargs: "OTHER_SWIFT_FLAGS=\"-D SNAPSHOT\""
   	)
  end
end
